name       : python-exif
version    : 1.4.2
release    : 5
source     :
    - https://pypi.io/packages/source/e/exif/exif-1.4.2.tar.gz : 8300324a52feb0090f1c0c28f55e2c5fdcf2560722b17b6620190b557160cec7
homepage   : https://gitlab.com/TNThieding/exif
license    : MIT
component  : programming.python
summary    : Read and modify image EXIF metadata using Python
description: |
    Read and modify image EXIF metadata using Python without any third-party software dependencies. For example, batch process image metadata using a Python script.
builddeps  :
    - python-plum
rundeps    :
    - python-plum
build      : |
    %python3_setup
install    : |
    %python3_install
