name       : python-exif
version    : 1.3.5
release    : 4
source     :
    - https://pypi.io/packages/source/e/exif/exif-1.3.5.tar.gz : 65541ac96697c59a7e0ea88f71deba9eff2c3680a07d23503980a9c3a70a4e9d
homepage   : https://gitlab.com/TNThieding/exif
license    : MIT
component  : programming.python
summary    : Read and modify image EXIF metadata using Python
description: |
    Read and modify image EXIF metadata using Python without any third-party software dependencies. For example, batch process image metadata using a Python script.
builddeps  :
    - python-plum
rundeps    :
    - python-plum
build      : |
    %python3_setup
install    : |
    %python3_install
