name       : python-exif
version    : 1.3.2
release    : 1
source     :
    - https://pypi.io/packages/source/e/exif/exif-1.3.2.tar.gz : 7a93ced12bca131b04c7e92c13a16a40685b9eb83414f9ed479d38df1c686633
license    : MIT
component  : programming.python
summary    : Read and modify image EXIF metadata using Python
description: |
    Read and modify image EXIF metadata using Python without any third-party software dependencies. For example, batch process image metadata using a Python script.
builddeps  :
    - python-plum
rundeps    :
    - python-plum
build      : |
    %python3_setup
install    : |
    %python3_install
